### PR TITLE
fixes line color change

### LINKED ISSUE #8: Fix line color picker (broken right now)
https://github.com/user-attachments/assets/59a48129-6308-42ef-997b-68d7c62cb5d4

### PR DESCRIPTION
**Pull request by swampie**
Fixes #8 
Changes line width on redraw to use the default width

### CODE REVIEW

File: src/services/select-service.ts [hunk 1]
```diff
@@ -99,12 +100,17 @@ export class SelectService {
...
       line.line, 
       line.coords, 
-      { color: newColor, width: line.line.width },
+      { color: newColor, width: LINE_DEFAULT_WIDTH },
       line.coords.length > 4
     );
+    
+    
+    
+
```
Comment (joaquimgamero) [inline src/services/select-service.ts]:
```suggestion
```

**Review by joaquimgamero — APPROVED** [review]
